name: Run Linux Docker Container on Windows Runner

on:
  push:
    branches:
      - main

jobs:
  run-linux-container-on-windows:
    runs-on: windows-latest
    
    steps:
      - name: Install Docker
        run: |
          # Install Docker if not installed (use Chocolatey package manager)
          choco install docker-cli
          choco install docker-desktop

      - name: Start Docker
        run: |
          # Start Docker service on Windows
          Start-Service docker

      - name: Check Docker Version
        run: docker --version

      - name: Pull and Run Linux Container
        run: |
          # Pull Ubuntu Linux image
          docker pull ubuntu:latest

          # Run a container in detached mode
          docker run -d --name linux-container ubuntu:latest

          # Check the OS type in the container
          docker exec linux-container uname -a

      - name: Clean Up
        run: |
          # Stop and remove the container
          docker stop linux-container
          docker rm linux-container
