name: Install Docker EE on Windows Runner

on:
  push:
    branches:
      - main

jobs:
  install-docker-ee:
    runs-on: windows-2022

    steps:
      - name: Enable Containers Feature
        run: |
          Install-WindowsFeature -Name Containers

      - name: Install Docker EE
        run: |
          # Install Docker Enterprise Edition on Windows
          Invoke-WebRequest -Uri https://download.docker.com/components/engine/windows-server/20.10/docker-20.10.14.zip -OutFile "$env:TEMP\docker.zip"
          Expand-Archive -Path "$env:TEMP\docker.zip" -DestinationPath "$env:ProgramFiles\Docker"
          
          # Add Docker to PATH
          [System.Environment]::SetEnvironmentVariable("Path", $env:Path + ";C:\Program Files\Docker", [System.EnvironmentVariableTarget]::Machine)
          
          # Install Docker service
          dockerd --register-service

      - name: Start Docker Service
        run: |
          Start-Service docker

      - name: Verify Docker Installation
        run: |
          docker --version
