name: Run Linux container on Windows runner

on:
  push:
    branches:
      - main

jobs:
  windows_job:
    runs-on: windows-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Set up Docker on Windows
        run: |
          # Verify if Docker is installed
          docker --version

      - name: Pull a Linux container (Ubuntu example)
        run: |
          # Pull Ubuntu Linux container from Docker Hub
          docker pull ubuntu:22.04

      - name: Run a Linux container
        run: |
          # Run commands inside a Linux container
          docker run -it ubuntu bash -c "echo 'Running from Linux container' && uname -a"

