name: Parallel Jobs Example

on: [push]

jobs:
  job1-windows:
    runs-on: windows-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Install OpenSSH Client
        run: |
          Add-WindowsCapability -Online -Name OpenSSH.Client*
      
      - name: Execute SSH command on Ubuntu runner
        run: |
          ssh -o StrictHostKeyChecking=no user@${{ needs.job2-ubuntu.outputs.ubuntu_ip }} "echo 'Hello from Windows runner!'"
          
    needs: job2-ubuntu

  job2-ubuntu:
    runs-on: ubuntu-latest
    outputs:
      ubuntu_ip: ${{ steps.get_ip.outputs.ubuntu_ip }}

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Get Ubuntu runner IP
        id: get_ip
        run: |
          echo "ubuntu_ip=$(hostname -I | awk '{print $1}')" >> $GITHUB_ENV
          echo "::set-output name=ubuntu_ip::$(hostname -I | awk '{print $1}')"

      - name: Set up SSH access for Windows runner
        run: |
          sudo apt-get update
          sudo apt-get install -y openssh-server
          sudo systemctl start ssh
          sudo mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PUBLIC_KEY }}" >> ~/.ssh/authorized_keys
          sudo systemctl restart ssh
