name: SSH into Docker Container on Windows Runner

on: [push]

jobs:
  windows-job:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Docker
        run: |
          choco install docker-cli
          Start-Service docker

      - name: Switch Docker to Linux container mode
        run: |
          & "$Env:ProgramFiles\Docker\Docker\DockerCli.exe" -SwitchLinuxEngine

      - name: Pull Ubuntu Docker Image
        run: |
          docker pull ubuntu:latest

      - name: Run Docker container with SSH server
        run: |
          docker run -d --name ssh_container -p 2222:22 ubuntu:latest
          docker exec ssh_container apt-get update
          docker exec ssh_container apt-get install -y openssh-server
          docker exec ssh_container service ssh start
          docker exec ssh_container mkdir /root/.ssh
          docker exec ssh_container bash -c "echo 'your-public-key-here' > /root/.ssh/authorized_keys"
      
      - name: Install OpenSSH Client on Windows
        run: |
          Add-WindowsCapability -Online -Name OpenSSH.Client*

      - name: SSH into Docker Container
        run: |
          ssh -o StrictHostKeyChecking=no root@localhost -p 2222
        shell: bash
